[package]
name = "compilation_bug_noir"
type = "bin"
authors = [""]
compiler_version = ">=0.23.0"

[dependencies]
mimc_sponge = {tag = "v0.0.2", git = "https://github.com/KumaCrypto/mimc_sponge_noir"}